# Generated by jeweler
lib = File.expand_path('../lib/', __FILE__)
$:.unshift lib unless $:.include?(lib)
require 'smqueue'

Gem::Specification.new do |s|
  s.name        = "metaphor"
  s.version     = SMQueue::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = [ "Sean O'Halpin", "Craig R Webster", "Chris O'Sullivan" ]
  s.email       = [ "craig@barkingiguana.com" ]
  s.homepage    = "http://github.com/seanohalpin/smqueue"
  s.summary     = "A simple interface for using message queues"
  s.description = "Provides a simple interface for using message " + \
  "queues with adapters for STOMP (through ActiveMQ), " + \
  "AMQP, XMPP PubSub, HTTP, Spread and stdio."

  s.required_rubygems_version = ">= 1.3.6"
  s.rubyforge_project         = "smqueue"

  s.files        = Dir.glob("{bin,lib}/**/*") + %w(LICENSE README.rdoc)
  s.require_path = 'lib'
end