mq: &default_mq
  :adapter: StompAdapter
#  :host: localhost
  :host: 192.168.53.134
  :port: 61613
  :reconnect_delay: 5

:announce:
  :adapter: SpreadAdapter
  :channel: 4803@localhost
  :group:   announce

:scheduler:
  <<: *default_mq
  :name: /queue/development.scheduler
  :reliable: true

:change_events:
  <<: *default_mq
  :name: /topic/change_events
  :reliable: true

:input:
  <<: *default_mq
  :name: /queue/shared
  :reliable: true

:output:
  <<: *default_mq
  :name: /queue/shared
  :reliable: true

:readline:
  :adapter: ReadlineAdapter

:stdio:
  :adapter: StdioAdapter

:error:
  :adapter: NullAdapter

:radq1:
  :adapter: StompAdapter
  :host: amq.dev2.rad0.net
  :port: 61613
  :reconnect_delay: 5
  :name: /topic/radq1
  :reliable: true

:radq2:
  :adapter: StompAdapter
  :host: amq.dev2.rad0.net
  :port: 61613
  :reconnect_delay: 5
  :name: /topic/radq2
  :reliable: true

:local1:
  :adapter: StompAdapter
  :host: localhost
  :port: 61613
  :reconnect_delay: 5
  :name: /topic/local1
  :reliable: true

:local2:
  :adapter: StompAdapter
  :host: localhost
  :port: 61613
  :reconnect_delay: 5
  :name: /topic/local2
  :reliable: true

