mq: &default_mq
  :adapter: StompAdapter
  :host: localhost
  :port: 61613
  :reconnect_delay: 5

:announce:
  :adapter: SpreadAdapter
  :channel: 4803@localhost
  :group:   announce

:scheduler:
  <<: *default_mq
  :name: /queue/development.scheduler
  :reliable: true

:change_events:
  <<: *default_mq
  :name: /topic/change_events
  :reliable: true

# :input:
#   <<: *default_mq
#   :name: /queue/shared
#   :reliable: true

# :output:
#   <<: *default_mq
#   :name: /queue/shared
#   :reliable: true

:input:
  :adapter: AMQPAdapter
  :name: amqpuser

:output:
  :adapter: AMQPAdapter
  :name: amqpuser

:readline:
  :adapter: ReadlineAdapter

:stdio:
  :adapter: StdioAdapter

:error:
  :adapter: NullAdapter

:null:
  :adapter: NullAdapter

:xmpp_pubsub_subscriber:
  :adapter: XMPPPubSubAdapter
  :host: localhost.private
  :service: pubsub
  :node: pub/updates
  :anonymous: true

:xmpp_pubsub_publisher:
  :adapter: XMPPPubSubAdapter
  :host: localhost.private
  :service: pubsub
  :node: pub/updates
  :jid: pub@localhost.private/pubsub
  :password: pub
  :debug: false

:radq1:
  :adapter: StompAdapter
  :host: amq.dev2.rad0.net
  :port: 61613
  :reconnect_delay: 5
  :name: /topic/radq1
  :reliable: true

:radq2:
  :adapter: StompAdapter
  :host: amq.dev2.rad0.net
  :port: 61613
  :reconnect_delay: 5
  :name: /topic/radq2
  :reliable: true

:local1:
  :adapter: StompAdapter
  :host: localhost
  :port: 61613
  :reconnect_delay: 5
  :name: /topic/local1
  :reliable: true

:local2:
  :adapter: StompAdapter
  :host: localhost
  :port: 61613
  :reconnect_delay: 5
  :name: /topic/local2
  :reliable: true

